import { Router } from "express";
import authRoutes from "./auth/auth.routes";
import userRoutes from "./users/users.routes";
import studentRoutes from "./students/students.routes";
import tutorRoutes from "./tutors/tutors.routes";
import schoolRoutes from "./schools/schools.routes";
import courseRoutes from "./courses/courses.routes";
import classroomRoutes from "./classrooms/classrooms.routes";
import liveRoutes from "./liveSessions/liveSessions.routes";
import recordingRoutes from "./recordings/recordings.routes";
import assessmentRoutes from "./assessments/assessments.routes";
import marketplaceRoutes from "./marketplace/marketplace.routes";
import orderRoutes from "./orders/orders.routes";
import subscriptionRoutes from "./subscriptions/subscriptions.routes";
import paymentRoutes from "./payments/payments.routes";
import notificationRoutes from "./notifications/notifications.routes";
import analyticsRoutes from "./analytics/analytics.routes";
import adminRoutes from "./admin/admin.routes";
import uploadRoutes from "./uploads/uploads.routes";
import bookingRoutes from "./bookings/bookings.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/users", userRoutes);
apiRouter.use("/students", studentRoutes);
apiRouter.use("/tutors", tutorRoutes);
apiRouter.use("/schools", schoolRoutes);
apiRouter.use("/courses", courseRoutes);
apiRouter.use("/classrooms", classroomRoutes);
apiRouter.use("/live-sessions", liveRoutes);
apiRouter.use("/recordings", recordingRoutes);
apiRouter.use("/assessments", assessmentRoutes);
apiRouter.use("/marketplace", marketplaceRoutes);
apiRouter.use("/orders", orderRoutes);
apiRouter.use("/subscriptions", subscriptionRoutes);
apiRouter.use("/payments", paymentRoutes);
apiRouter.use("/notifications", notificationRoutes);
apiRouter.use("/analytics", analyticsRoutes);
apiRouter.use("/admin", adminRoutes);
apiRouter.use("/uploads", uploadRoutes);
apiRouter.use("/bookings", bookingRoutes);
