/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as SchoolDashboardRouteImport } from './routes/school-dashboard'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AccountSuccessRouteImport } from './routes/account-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as TutorStudentsRouteImport } from './routes/tutor.students'
import { Route as TutorSettingsRouteImport } from './routes/tutor.settings'
import { Route as TutorReviewsRouteImport } from './routes/tutor.reviews'
import { Route as TutorRecordedLessonsRouteImport } from './routes/tutor.recorded-lessons'
import { Route as TutorNotificationsRouteImport } from './routes/tutor.notifications'
import { Route as TutorMarketplaceRouteImport } from './routes/tutor.marketplace'
import { Route as TutorLiveSessionsRouteImport } from './routes/tutor.live-sessions'
import { Route as TutorEarningsRouteImport } from './routes/tutor.earnings'
import { Route as TutorClassesRouteImport } from './routes/tutor.classes'
import { Route as TutorCalendarRouteImport } from './routes/tutor.calendar'
import { Route as TutorAssignmentsRouteImport } from './routes/tutor.assignments'
import { Route as TutorAssessmentsRouteImport } from './routes/tutor.assessments'
import { Route as TutorLiveSessionsSessionIdRouteImport } from './routes/tutor.live-sessions.$sessionId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolDashboardRoute = SchoolDashboardRouteImport.update({
  id: '/school-dashboard',
  path: '/school-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSuccessRoute = AccountSuccessRouteImport.update({
  id: '/account-success',
  path: '/account-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRoute,
} as any)
const TutorStudentsRoute = TutorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TutorRoute,
} as any)
const TutorSettingsRoute = TutorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TutorRoute,
} as any)
const TutorReviewsRoute = TutorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TutorRoute,
} as any)
const TutorRecordedLessonsRoute = TutorRecordedLessonsRouteImport.update({
  id: '/recorded-lessons',
  path: '/recorded-lessons',
  getParentRoute: () => TutorRoute,
} as any)
const TutorNotificationsRoute = TutorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TutorRoute,
} as any)
const TutorMarketplaceRoute = TutorMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => TutorRoute,
} as any)
const TutorLiveSessionsRoute = TutorLiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => TutorRoute,
} as any)
const TutorEarningsRoute = TutorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TutorRoute,
} as any)
const TutorClassesRoute = TutorClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TutorRoute,
} as any)
const TutorCalendarRoute = TutorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAssignmentsRoute = TutorAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TutorRoute,
} as any)
const TutorAssessmentsRoute = TutorAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => TutorRoute,
} as any)
const TutorLiveSessionsSessionIdRoute =
  TutorLiveSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => TutorLiveSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-success': typeof AccountSuccessRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-dashboard': typeof SchoolDashboardRoute
  '/tutor': typeof TutorRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/tutor/assessments': typeof TutorAssessmentsRoute
  '/tutor/assignments': typeof TutorAssignmentsRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/classes': typeof TutorClassesRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/live-sessions': typeof TutorLiveSessionsRouteWithChildren
  '/tutor/marketplace': typeof TutorMarketplaceRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/recorded-lessons': typeof TutorRecordedLessonsRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/live-sessions/$sessionId': typeof TutorLiveSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-success': typeof AccountSuccessRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-dashboard': typeof SchoolDashboardRoute
  '/verify-email': typeof VerifyEmailRoute
  '/tutor/assessments': typeof TutorAssessmentsRoute
  '/tutor/assignments': typeof TutorAssignmentsRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/classes': typeof TutorClassesRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/live-sessions': typeof TutorLiveSessionsRouteWithChildren
  '/tutor/marketplace': typeof TutorMarketplaceRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/recorded-lessons': typeof TutorRecordedLessonsRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutor': typeof TutorIndexRoute
  '/tutor/live-sessions/$sessionId': typeof TutorLiveSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-success': typeof AccountSuccessRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-dashboard': typeof SchoolDashboardRoute
  '/tutor': typeof TutorRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/tutor/assessments': typeof TutorAssessmentsRoute
  '/tutor/assignments': typeof TutorAssignmentsRoute
  '/tutor/calendar': typeof TutorCalendarRoute
  '/tutor/classes': typeof TutorClassesRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/live-sessions': typeof TutorLiveSessionsRouteWithChildren
  '/tutor/marketplace': typeof TutorMarketplaceRoute
  '/tutor/notifications': typeof TutorNotificationsRoute
  '/tutor/recorded-lessons': typeof TutorRecordedLessonsRoute
  '/tutor/reviews': typeof TutorReviewsRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/live-sessions/$sessionId': typeof TutorLiveSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-success'
    | '/admin-dashboard'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/school-dashboard'
    | '/tutor'
    | '/verify-email'
    | '/tutor/assessments'
    | '/tutor/assignments'
    | '/tutor/calendar'
    | '/tutor/classes'
    | '/tutor/earnings'
    | '/tutor/live-sessions'
    | '/tutor/marketplace'
    | '/tutor/notifications'
    | '/tutor/recorded-lessons'
    | '/tutor/reviews'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor/'
    | '/tutor/live-sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-success'
    | '/admin-dashboard'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/school-dashboard'
    | '/verify-email'
    | '/tutor/assessments'
    | '/tutor/assignments'
    | '/tutor/calendar'
    | '/tutor/classes'
    | '/tutor/earnings'
    | '/tutor/live-sessions'
    | '/tutor/marketplace'
    | '/tutor/notifications'
    | '/tutor/recorded-lessons'
    | '/tutor/reviews'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor'
    | '/tutor/live-sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/account-success'
    | '/admin-dashboard'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/school-dashboard'
    | '/tutor'
    | '/verify-email'
    | '/tutor/assessments'
    | '/tutor/assignments'
    | '/tutor/calendar'
    | '/tutor/classes'
    | '/tutor/earnings'
    | '/tutor/live-sessions'
    | '/tutor/marketplace'
    | '/tutor/notifications'
    | '/tutor/recorded-lessons'
    | '/tutor/reviews'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutor/'
    | '/tutor/live-sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSuccessRoute: typeof AccountSuccessRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolDashboardRoute: typeof SchoolDashboardRoute
  TutorRoute: typeof TutorRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-dashboard': {
      id: '/school-dashboard'
      path: '/school-dashboard'
      fullPath: '/school-dashboard'
      preLoaderRoute: typeof SchoolDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-success': {
      id: '/account-success'
      path: '/account-success'
      fullPath: '/account-success'
      preLoaderRoute: typeof AccountSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/students': {
      id: '/tutor/students'
      path: '/students'
      fullPath: '/tutor/students'
      preLoaderRoute: typeof TutorStudentsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/settings': {
      id: '/tutor/settings'
      path: '/settings'
      fullPath: '/tutor/settings'
      preLoaderRoute: typeof TutorSettingsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/reviews': {
      id: '/tutor/reviews'
      path: '/reviews'
      fullPath: '/tutor/reviews'
      preLoaderRoute: typeof TutorReviewsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/recorded-lessons': {
      id: '/tutor/recorded-lessons'
      path: '/recorded-lessons'
      fullPath: '/tutor/recorded-lessons'
      preLoaderRoute: typeof TutorRecordedLessonsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/notifications': {
      id: '/tutor/notifications'
      path: '/notifications'
      fullPath: '/tutor/notifications'
      preLoaderRoute: typeof TutorNotificationsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/marketplace': {
      id: '/tutor/marketplace'
      path: '/marketplace'
      fullPath: '/tutor/marketplace'
      preLoaderRoute: typeof TutorMarketplaceRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/live-sessions': {
      id: '/tutor/live-sessions'
      path: '/live-sessions'
      fullPath: '/tutor/live-sessions'
      preLoaderRoute: typeof TutorLiveSessionsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/earnings': {
      id: '/tutor/earnings'
      path: '/earnings'
      fullPath: '/tutor/earnings'
      preLoaderRoute: typeof TutorEarningsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/classes': {
      id: '/tutor/classes'
      path: '/classes'
      fullPath: '/tutor/classes'
      preLoaderRoute: typeof TutorClassesRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/calendar': {
      id: '/tutor/calendar'
      path: '/calendar'
      fullPath: '/tutor/calendar'
      preLoaderRoute: typeof TutorCalendarRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/assignments': {
      id: '/tutor/assignments'
      path: '/assignments'
      fullPath: '/tutor/assignments'
      preLoaderRoute: typeof TutorAssignmentsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/assessments': {
      id: '/tutor/assessments'
      path: '/assessments'
      fullPath: '/tutor/assessments'
      preLoaderRoute: typeof TutorAssessmentsRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/live-sessions/$sessionId': {
      id: '/tutor/live-sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/tutor/live-sessions/$sessionId'
      preLoaderRoute: typeof TutorLiveSessionsSessionIdRouteImport
      parentRoute: typeof TutorLiveSessionsRoute
    }
  }
}

interface TutorLiveSessionsRouteChildren {
  TutorLiveSessionsSessionIdRoute: typeof TutorLiveSessionsSessionIdRoute
}

const TutorLiveSessionsRouteChildren: TutorLiveSessionsRouteChildren = {
  TutorLiveSessionsSessionIdRoute: TutorLiveSessionsSessionIdRoute,
}

const TutorLiveSessionsRouteWithChildren =
  TutorLiveSessionsRoute._addFileChildren(TutorLiveSessionsRouteChildren)

interface TutorRouteChildren {
  TutorAssessmentsRoute: typeof TutorAssessmentsRoute
  TutorAssignmentsRoute: typeof TutorAssignmentsRoute
  TutorCalendarRoute: typeof TutorCalendarRoute
  TutorClassesRoute: typeof TutorClassesRoute
  TutorEarningsRoute: typeof TutorEarningsRoute
  TutorLiveSessionsRoute: typeof TutorLiveSessionsRouteWithChildren
  TutorMarketplaceRoute: typeof TutorMarketplaceRoute
  TutorNotificationsRoute: typeof TutorNotificationsRoute
  TutorRecordedLessonsRoute: typeof TutorRecordedLessonsRoute
  TutorReviewsRoute: typeof TutorReviewsRoute
  TutorSettingsRoute: typeof TutorSettingsRoute
  TutorStudentsRoute: typeof TutorStudentsRoute
  TutorIndexRoute: typeof TutorIndexRoute
}

const TutorRouteChildren: TutorRouteChildren = {
  TutorAssessmentsRoute: TutorAssessmentsRoute,
  TutorAssignmentsRoute: TutorAssignmentsRoute,
  TutorCalendarRoute: TutorCalendarRoute,
  TutorClassesRoute: TutorClassesRoute,
  TutorEarningsRoute: TutorEarningsRoute,
  TutorLiveSessionsRoute: TutorLiveSessionsRouteWithChildren,
  TutorMarketplaceRoute: TutorMarketplaceRoute,
  TutorNotificationsRoute: TutorNotificationsRoute,
  TutorRecordedLessonsRoute: TutorRecordedLessonsRoute,
  TutorReviewsRoute: TutorReviewsRoute,
  TutorSettingsRoute: TutorSettingsRoute,
  TutorStudentsRoute: TutorStudentsRoute,
  TutorIndexRoute: TutorIndexRoute,
}

const TutorRouteWithChildren = TutorRoute._addFileChildren(TutorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSuccessRoute: AccountSuccessRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolDashboardRoute: SchoolDashboardRoute,
  TutorRoute: TutorRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
